apiVersion: platform.confluent.io/v1beta1
kind: FlinkApplication
metadata:
  name: flink-app
  namespace: confluent
spec:
  flinkEnvironment: flink-env
  image: confluentinc/cp-flink:1.19.1-cp2
  flinkVersion: v1_19
  serviceAccount: flink
  flinkConfiguration:
    # metrics.reporter.prom.factory.class: "org.apache.flink.metrics.prometheus.PrometheusReporterFactory"
    # metrics.reporter.prom.port": "9249"
    rest.profiling.enabled: "true"
    fs.azure.enabled: "true"

    state.checkpoints.dir: wasbs://<container>@<storage-account>.blob.core.windows.net/checkpoint/
    fs.azure.account.key.<storage-account>.blob.core.windows.net: <azure-access-key>
    fs.azure.write.request.size: ""
    fs.azure.read.request.size: ""
    execution.checkpointing.interval: ""
    execution.checkpoint.mode: EXACTLY_ONCE
    execution.checkpointing.timeout: ""  # in ms
    execution.checkpointing.max-concurrent-checkpoints: "1"

    state.backend: rocksdb
    state.backend.incremental: "true"
    # state.backend.rocksdb.localdir: /localstatedir

    state.backend.rocksdb.memory.managed: "true"
    taskmanager.memory.managed.size: ""
    taskmanager.memory.task.heap.size: ""

    state.backend.rocksdb.block.blocksize: ""
    state.backend.rocksdb.writebuffer.size: ""
    state.backend.rocksdb.writebuffer.count: ""
    state.backend.rocksdb.compaction.style: ""
    state.backend.rocksdb.compression.type: ""

    taskmanager.numberOfTaskSlots: "8"
    
  podTemplate:
    spec:
      containers:
          - name: flink-main-container
            env:
              - name: ENABLE_BUILT_IN_PLUGINS
                value: "flink-azure-fs-hadoop-1.19.1-cp2.jar"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app-confluent
                    operator: In
                    values:
                      - taskmanager
  jobManager:
    resource:
      memory: 1048m
      cpu: 1
  taskManager:
    replicas: 3
    resource:
      memory: 128G
      cpu: 16
    # podTemplate:
    #   spec:
    #     volumes:
    #       - name: rocksdb-storage
    #         emptyDir: {}
    #     containers:
    #       - name: flink-main-container
    #         volumeMounts:
    #           - name: rocksdb-storage
    #             mountPath: /localstatedir

  job:
    # Built-in-example
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    state: running
    parallelism: 3
    upgradeMode: stateless
  cmfRestClassRef:
    name: default
    namespace: confluent
