# Create a Config map. Sample below:
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-kerberos-config
  namespace: confluent
data:
  krb5.conf: |
    [libdefaults]
      default_realm = example.com
      udp_preference_limit = 1

    [realms]
      example.com = {
        kdc = kdc01.example.com
        admin_server = kdc01.example.com
      }

    [domain_realm]
      .example.com = example.com
      example.com = example.com
