apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-server-cert
  namespace: xp
spec:
  secretName: tls-kafka
  duration: 43800h
  renewBefore: 720h
  commonName: kafka
  ipAddresses:
    - <LB IP>
  dnsNames:
    - kafka
    - kafka.xp.svc.cluster.local
    - kafka-0.kafka.xp.svc.cluster.local
    - kafka-1.kafka.xp.svc.cluster.local
    - kafka-2.kafka.xp.svc.cluster.local
    - kraftcontroller.xp.svc.cluster.local
    - kraftcontroller-0.kraftcontroller.xp.svc.cluster.local
    - kraftcontroller-1.kraftcontroller.xp.svc.cluster.local
    - kraftcontroller-2.kraftcontroller.xp.svc.cluster.local
    - zookeeper.xp.svc.cluster.local
    - *.zookeeper.xp.svc.cluster.local
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: kafka-ca-issuer
    kind: Issuer