apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: xp
spec:
  isCA: true
  commonName: TestCA
  secretName: root-ca-secret
  duration: 43800h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigning-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigning-issuer
  namespace: xp
spec:
  selfSigned: {}