apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: confluent-storage
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS     
  kind: Managed
  cachingMode: ReadOnly    
reclaimPolicy: Retain      
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true