{
 "title": "Flink Dashboard",
 "description": "Flink Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "tm_id",
    "label": "Tm ID",
    "query": "label_values(flink_taskmanager_job_task_operator_numRecordsInPerSecond ,tm_id)"
   },
   {
    "name": "host",
    "label": "Job Host",
    "query": "label_values(flink_taskmanager_job_task_operator_numRecordsInPerSecond ,host)"
   },
   {
    "name": "task_name",
    "label": "Task name",
    "query": "label_values(flink_taskmanager_job_task_operator_numRecordsInPerSecond ,task_name)"
   },
   {
    "name": "operator_name",
    "label": "operator_name",
    "query": "label_values(flink_taskmanager_job_task_operator_numRecordsInPerSecond ,operator_name)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job Uptime",
   "type": "stat",
   "description": "The time that the job has been running without interruption.\nReturns -1 for completed jobs (in milliseconds).",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flink_jobmanager_job_uptime" }
   ]
  },
  {
   "title": "# Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Job Downtime",
   "type": "stat",
   "description": "For jobs currently in a failing/recovering situation, the time elapsed during this outage.\nReturns 0 for running jobs and -1 for completed jobs (in milliseconds).",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flink_jobmanager_job_downtime" }
   ]
  },
  {
   "title": "Job Full Restarts",
   "type": "stat",
   "description": "The total number of full restarts since this job was submitted. Attention: Since 1.9.2, this metric also includes fine-grained restarts.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_fullRestarts",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Job restartingTime",
   "type": "stat",
   "description": "The time it took to restart the job, or how long the current restart has been in progress (in milliseconds).\t",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_restartingTime"
    }
   ]
  },
  {
   "title": "# Registered TM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "# Task Slots Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "# Task Slots Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Latest event watermark under processing by slowest task",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "bottomk(1, flink_taskmanager_job_task_currentInputWatermark > 0 )"
    }
   ]
  },
  {
   "title": "Checkpointing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpointing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_numberOfFailedCheckpoints",
       "legendFormat": "failed"
      },
      {
       "expr": "flink_jobmanager_job_numberOfInProgressCheckpoints",
       "legendFormat": "in progress"
      },
      {
       "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints",
       "legendFormat": "completed"
      },
      {
       "expr": "flink_jobmanager_job_totalNumberOfCheckpoints",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Checkpointing Size",
     "type": "timeseries",
     "description": "The number of buffered bytes during alignment over all subtasks for the last checkpoint (in bytes).\nThe total size of the last checkpoint (in bytes).\t",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointAlignmentBuffered",
       "legendFormat": "lastCheckpointAlignmentBuffered"
      },
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize",
       "legendFormat": "lastCheckpointSize"
      }
     ]
    },
    {
     "title": "Last CP Duration",
     "type": "stat",
     "description": "The time it took to complete the last checkpoint (in milliseconds).",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration"
      }
     ]
    },
    {
     "title": "Last Restore timestamp",
     "type": "stat",
     "description": "Timestamp when the last checkpoint was restored at the coordinator (in milliseconds).",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointRestoreTimestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobmanager Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "JobManager JVM Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed",
       "legendFormat": "direct mem used"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_TotalCapacity",
       "legendFormat": "direct total capacity"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Mapped_MemoryUsed",
       "legendFormat": "mapped mem used"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Mapped_TotalCapacity",
       "legendFormat": "mapped total capacity"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Committed",
       "legendFormat": "heap mem commited"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max",
       "legendFormat": "heap mem max"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "heap mem used"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Committed",
       "legendFormat": "nonheap mem committed"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Max",
       "legendFormat": "nonheap mem max"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
       "legendFormat": "nonheap mem used"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_Count",
       "legendFormat": "direct_count"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Mapped_Count",
       "legendFormat": "mapped_count"
      }
     ]
    },
    {
     "title": "JobManager GC (rate 1m interval)",
     "type": "timeseries",
     "description": "The total number of collections that have occurred.\t\nThe total time spent performing garbage collection.\t",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "rate(flink_jobmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Count[1m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(flink_jobmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JobManager JVM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Threads_Count",
       "legendFormat": "threads count"
      },
      {
       "expr": "rate(flink_jobmanager_Status_JVM_CPU_Time[1m])",
       "legendFormat": "cpu time (rate 1m)"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Load",
       "legendFormat": "cpu load"
      }
     ]
    },
    {
     "title": "Classes Loaded/Unloaded",
     "type": "timeseries",
     "description": "The total number of classes loaded since the start of the JVM.  \nThe total number of classes unloaded since the start of the JVM.\t",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_ClassLoader_ClassesLoaded",
       "legendFormat": "classes loaded"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_ClassLoader_ClassesUnloaded",
       "legendFormat": "classes unloaded"
      }
     ]
    }
   ]
  },
  {
   "title": "TaskManager Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Manager GC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Count{tm_id=~\"$tm_id\"}[1m])",
       "legendFormat": "gc ps marksweep count - $tm_id"
      },
      {
       "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time{tm_id=~\"$tm_id\"}[1m])",
       "legendFormat": "gc ps marksweep time - $tm_id"
      }
     ]
    },
    {
     "title": "JVM_CPU_Load",
     "type": "timeseries",
     "description": "The recent CPU usage of the JVM.\t",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 40 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load{tm_id=~\"$tm_id\"}"
      }
     ]
    },
    {
     "title": "JVM_CPU_Time",
     "type": "timeseries",
     "description": "The CPU time used by the JVM.\t",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_Status_JVM_CPU_Time{tm_id=~\"$tm_id\"}[1m])",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "JVM_Threads_Count",
     "type": "timeseries",
     "description": "The total number of live threads.\t",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 40 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Threads_Count{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "ClassLoader",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_ClassLoader_ClassesLoaded{tm_id=~\"$tm_id\"}",
       "legendFormat": "loaded"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_ClassLoader_ClassesUnloaded{tm_id=\"$tm_id\"}",
       "legendFormat": "unloaded"
      }
     ]
    },
    {
     "title": "Shuffle_Netty_TotalMemorySegments",
     "type": "timeseries",
     "description": "The number of allocated memory segments.\t",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemorySegments{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Shuffle_Netty_AvailableMemorySegments",
     "type": "timeseries",
     "description": "The number of unused memory segments.\t",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 44 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemorySegments{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "TaskManager JVM Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{tm_id=~\"$tm_id\"}",
       "legendFormat": "direct mem used - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity{tm_id=\"$tm_id\"}",
       "legendFormat": "direct total capacity - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_MemoryUsed{tm_id=\"$tm_id\"}",
       "legendFormat": "mapped mem used - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_TotalCapacity{tm_id=\"$tm_id\"}",
       "legendFormat": "mapped total capacity - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Committed{tm_id=\"$tm_id\"}",
       "legendFormat": "heap mem commited - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max{tm_id=\"$tm_id\"}",
       "legendFormat": "heap mem max - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{tm_id=\"$tm_id\"}",
       "legendFormat": "heap mem used - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Committed{tm_id=\"$tm_id\"}",
       "legendFormat": "nonheap mem committed - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Max{tm_id=\"$tm_id\"}",
       "legendFormat": "nonheap mem max - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used{tm_id=\"$tm_id\"}",
       "legendFormat": "nonheap mem used - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_Count{tm_id=\"$tm_id\"}",
       "legendFormat": "direct_count - $tm_id"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_Count{tm_id=\"$tm_id\"}",
       "legendFormat": "mapped_count - $tm_id"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 slowest operators (based on current INPUT watermark)",
     "type": "table",
     "description": "The last watermark this operator/tasks has received (in milliseconds).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "bottomk(10, flink_taskmanager_job_task_operator_currentInputWatermark > 0 )",
       "legendFormat": "{{task_name}} - {{tm_id}}"
      }
     ]
    },
    {
     "title": "Top 10 slowest tasks (based on current INPUT watermark)",
     "type": "table",
     "description": "The last watermark this operator/tasks has received (in milliseconds).",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "bottomk(10, flink_taskmanager_job_task_operator_currentInputWatermark > 0 )",
       "legendFormat": "{{task_name}} - {{tm_id}}"
      }
     ]
    },
    {
     "title": "Top 10 slowest tasks (based on current OUTPUT watermark)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "bottomk(10, flink_taskmanager_job_task_operator_currentOutputWatermark > 0 )",
       "legendFormat": "{{task_name}} - {{tm_id}}"
      }
     ]
    },
    {
     "title": "Top 10 slowest tasks (based on current OUTPUT watermark)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "bottomk(10, flink_taskmanager_job_task_operator_currentOutputWatermark > 0 )",
       "legendFormat": "{{task_name}} - {{tm_id}}"
      }
     ]
    },
    {
     "title": "Num Late Records Dropped (timeWindow operators) 1min rate",
     "type": "timeseries",
     "description": "The number of records this operator/task has dropped due to arriving late. Only operators using timeWindow()",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_numLateRecordsDropped[1m])) by (operator_name)",
       "legendFormat": "{{ operator_name }}"
      }
     ]
    },
    {
     "title": "numRecordsInPerSecond",
     "type": "timeseries",
     "description": "The number of records this operator/task receives per second.\t",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond) by (operator_name)",
       "legendFormat": "{{operator_name}}"
      }
     ]
    },
    {
     "title": "numRecordsOutPerSecond",
     "type": "timeseries",
     "description": "The number of records this operator/task sends per second.\t",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond) by (operator_name)",
       "legendFormat": "{{operator_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 slowest tasks (based on current input watermark)",
     "type": "table",
     "description": "The last watermark this operator/tasks has received (in milliseconds).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "bottomk(10, flink_taskmanager_job_task_currentInputWatermark > 0 )",
       "legendFormat": "{{task_name}} - {{tm_id}}"
      }
     ]
    },
    {
     "title": "Top 10 fastest tasks (based on current input watermark)",
     "type": "table",
     "description": "The last watermark this operator/tasks has received (in milliseconds).",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "topk(10, flink_taskmanager_job_task_currentInputWatermark > 0 )",
       "legendFormat": "{{task_name}} - {{tm_id}}"
      }
     ]
    },
    {
     "title": "isBackPressured",
     "type": "timeseries",
     "description": "Whether the task is back-pressured.\n1 - yes. 0 - no",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_isBackPressured > 0",
       "legendFormat": "{{ tm_id}} - {{task_name}}"
      }
     ]
    },
    {
     "title": "idleTimeMsPerSecond",
     "type": "timeseries",
     "description": "The time (in milliseconds) this task is idle (either has no data to process or it is back pressured) per second.\t",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_idleTimeMsPerSecond) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "checkpointAlignmentTime",
     "type": "timeseries",
     "description": "The time in nanoseconds that the last barrier alignment took to complete, or how long the current alignment has taken so far (in nanoseconds).\t",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_checkpointAlignmentTime) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "checkpointStartDelayNanos",
     "type": "timeseries",
     "description": "The time in nanoseconds that elapsed between the creation of the last checkpoint and the time when the checkpointing process has started by this Task. This delay shows how long it takes for the first checkpoint barrier to reach the task. A high value indicates back-pressure. If only a specific task has a long start delay, the most likely reason is data skew.\t",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_checkpointStartDelayNanos",
       "legendFormat": "{{task_name}} - {{tm_id}}"
      }
     ]
    },
    {
     "title": "numBytesInPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numBytesInPerSecond) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "numBytesOutPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numBytesOutPerSecond) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "numRecordsInPerSecond",
     "type": "timeseries",
     "description": "The number of records this operator/task receives per second.\t",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "numRecordsOutPerSecond",
     "type": "timeseries",
     "description": "The number of records this operator/task sends per second.\t",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "numBuffersOutPerSecond",
     "type": "timeseries",
     "description": "The number of network buffers this task emits per second.\t",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numBuffersOutPerSecond) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Netty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Bytes Local/Remote per second",
     "type": "timeseries",
     "description": "The number of bytes this task reads from a local source per second.\t\nThe number of bytes this task reads from a remote source per second.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocalPerSecond) by (task_name)",
       "legendFormat": "Local - {{task_name}}"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemotePerSecond) by (task_name)",
       "legendFormat": "Remote - {{task_name}}"
      }
     ]
    },
    {
     "title": "# Buffers in Local/Remote per second",
     "type": "timeseries",
     "description": "The total number of network buffers this task has read from a local source.\t\nThe total number of network buffers this task has read from a remote source.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocalPerSecond) by (task_name)",
       "legendFormat": "Local - {{task_name}}"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemotePerSecond) by (task_name)",
       "legendFormat": "Remote - {{task_name}}"
      }
     ]
    },
    {
     "title": "Shuffle.Netty.Input.Buffers.inPoolUsage",
     "type": "timeseries",
     "description": "inPoolUsage  - An estimate of the input buffers usage.\t\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inPoolUsage) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Shuffle.Netty.Input.Buffers.inputQueueLength",
     "type": "timeseries",
     "description": "The number of queued input buffers.\t",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputQueueLength) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Shuffle.Netty.Input.Buffers.inputExclusiveBuffersUsage",
     "type": "timeseries",
     "description": "An estimate of the exclusive input buffers usage. (ignores LocalInputChannels)\t",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 102 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputExclusiveBuffersUsage) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Shuffle.Netty.Input.Buffers.inputFloatingBuffersUsage",
     "type": "timeseries",
     "description": "An estimate of the floating input buffers usage. (ignores LocalInputChannels)\t",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputFloatingBuffersUsage) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Shuffle.Netty.Output.Buffers.outPoolUsage",
     "type": "timeseries",
     "description": "An estimate of the output buffers usage.\t",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outPoolUsage) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Shuffle.Netty.Output.Buffers.outputQueueLength",
     "type": "timeseries",
     "description": "The number of queued output buffers.\t",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outputQueueLength) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    }
   ]
  }
 ]
}