apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: flink 
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
    - port: 3000         # Exposed port on LB
      targetPort: 3000 # Grafana default port in container
      protocol: TCP
      name: http