apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: flink  
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus  
  ports:
    - port: 80           # External port exposed by LoadBalancer
      targetPort: 9090   # Prometheus web UI port inside pod
      protocol: TCP
      name: http
