apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pageviews
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
    namespace: confluent
  configs:
    kafka.topic: "pageviews"
    quickstart: "pageviews"
    auto.create: "true"
    auto.create.topics.enable: "true"

    # --- Avro Serialization ---
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "https://schemaregistry.confluent.svc.cluster.local:8081"
    key.converter.schema.registry.ssl.truststore.location: "/mnt/sslcerts/truststore.p12"
    key.converter.schema.registry.ssl.truststore.password: "mystorepassword"
    key.converter.schema.registry.ssl.truststore.type: "PKCS12"
    
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "https://schemaregistry.confluent.svc.cluster.local:8081"
    value.converter.schema.registry.ssl.truststore.location: "/mnt/sslcerts/truststore.p12"
    value.converter.schema.registry.ssl.truststore.password: "mystorepassword"
    value.converter.schema.registry.ssl.truststore.type: "PKCS12"

    topic.creation.enable: "true"
    topic.creation.default.replication.factor: "3"
    topic.creation.default.partitions: "3"
    topic.creation.default.cleanup.policy: "delete"

    # Optional (if using SR auth)
    # key.converter.basic.auth.credentials.source: "USER_INFO"
    # key.converter.basic.auth.user.info: "user:password"
    # value.converter.basic.auth.credentials.source: "USER_INFO"
    # value.converter.basic.auth.user.info: "user:password"

    max.interval: "100"
    iterations: "10000000"








