apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: topic-manager
  namespace: xp
spec:
  principal:
    type: user
    name: kafkaclient
  role: DeveloperManager
  resourcePatterns:
    - name: test-topic
      resourceType: Topic
      patternType: LITERAL
