apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: topic-writer
  namespace: xp 
spec:
  principal:
    type: user
    name: kafkaclient # <username>
  role: DeveloperWrite
  resourcePatterns:
    - name: test-topic # <topic-name>
      resourceType: Topic
      patternType: LITERAL
