apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: confluent
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: "kraftcontroller"
        static_configs:
          - targets:
              - "kraftcontroller-0-internal.confluent.svc.tz.cluster.local:7778"
              - "kraftcontroller-1-internal.confluent.svc.tz.cluster.local:7778"
              - "kraftcontroller-2-internal.confluent.svc.tz.cluster.local:7778"
            labels:
              kubernetes_namespace: confluent
              platform_confluent_io_type: kraftcontroller
              app: kraftcontroller
        relabel_configs:
          - source_labels: [__address__]
            target_label: hostname
            regex: '([^:]+)(:[0-9]+)?'
            replacement: '${1}'

      - job_name: "kafka-broker"
        static_configs:
          - targets:
              - "kafka-0-internal.confluent.svc.tz.cluster.local:7778"
              - "kafka-1-internal.confluent.svc.tz.cluster.local:7778"
              - "kafka-2-internal.confluent.svc.tz.cluster.local:7778"
            labels:
              kubernetes_namespace: confluent
              platform_confluent_io_type: kafka
              app: kafka
        relabel_configs:
          - source_labels: [__address__]
            target_label: hostname
            regex: '([^:]+)(:[0-9]+)?'
            replacement: '${1}'
